"""добавление информации о файле

Revision ID: 306c25497aff
Revises: 4e602019c704
Create Date: 2026-05-04 16:45:52.848427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '306c25497aff'
down_revision: Union[str, Sequence[str], None] = '4e602019c704'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.alter_column('contract', 'file_name', nullable=True)
    op.alter_column('contract','file_path',nullable=True )
    op.add_column('contract', sa.Column('file_time',sa.DateTime, nullable=True))


    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contract', 'file_name', nullable=False)
    op.alter_column('contract', 'file_path',  nullable=False)
    op.drop_column('contract', 'file_time')

    # ### end Alembic commands ###
