"""В таблице заявки поле саlculate_price необязательное

Revision ID: 4e602019c704
Revises: 06d6fc5bbeba
Create Date: 2026-05-01 14:23:29.096385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4e602019c704'
down_revision: Union[str, Sequence[str], None] = '06d6fc5bbeba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('application','calculate_price', nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('application', 'calculate_price', nullable=False)

    # ### end Alembic commands ###
