"""Добавление статуса в таблицу contract

Revision ID: 9055ce130b5b
Revises: 306c25497aff
Create Date: 2026-05-05 18:15:03.131893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9055ce130b5b'
down_revision: Union[str, Sequence[str], None] = '306c25497aff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract', sa.Column('status_contract', sa.String,nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contract','status_contract')

    # ### end Alembic commands ###
